version: "3.9"

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME:-scrap_db}
      POSTGRES_USER: ${DB_USER:-scrap_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-scrap_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-scrap_user} -d ${DB_NAME:-scrap_db}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env         # shared root env
      - ./backend/.env # optional backend-specific overrides
    environment:
      DATABASE_URL: postgresql://${DB_USER:-scrap_user}:${DB_PASSWORD:-scrap_password}@db:5432/${DB_NAME:-scrap_db}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-scrap_db}
      DB_USER: ${DB_USER:-scrap_user}
      DB_PASSWORD: ${DB_PASSWORD:-scrap_password}
      PORT: 3001
      NODE_ENV: development
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3001:3001"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./frontend/public:/app/frontend/public # Added this line to mount frontend/public
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm install && npm run build && npm run migrate && npm start"

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env          # shared root env
      - ./frontend/.env # optional frontend-specific overrides
    environment:
      VITE_API_BASE_URL: http://localhost:3001 # Corrected to use host's exposed port
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/index.html:/app/index.html
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data: