import React, { useState, useEffect, useRef } from 'react';
import { EmbeddableForm } from './EmbeddableForm';
import { FormData, GeneratedForm, SaaSForm, FormField } from '../types/api';

// Helper to determine if a color is light (simplified for demo)
const isLightColor = (color: string): boolean => {
  if (!color) return false;
  let r, g, b;

  // Handle hex colors
  if (color.startsWith('#')) {
    const hex = color.slice(1);
    if (hex.length === 3) { // #rgb
      r = parseInt(hex[0] + hex[0], 16);
      g = parseInt(hex[1] + hex[1], 16);
      b = parseInt(hex[2] + hex[2], 16);
    } else if (hex.length === 6) { // #rrggbb
      r = parseInt(hex.substring(0, 2), 16);
      g = parseInt(hex.substring(2, 4), 16);
      b = parseInt(hex.substring(4, 6), 16);
    } else {
      return false;
    }
  } 
  // Handle rgb/rgba colors
  else if (color.startsWith('rgb')) {
    const parts = color.match(/\d+/g)?.map(Number);
    if (parts && parts.length >= 3) {
      [r, g, b] = parts;
    } else {
      return false;
    }
  }
  // Handle hsl/hsla colors
  else if (color.startsWith('hsl')) {
    // For simplicity, treat HSL as dark if lightness is low
    const lightnessMatch = color.match(/hsla?\(\s*\d+\s*,\s*\d+%\s*,\s*(\d+)%\s*(?:,\s*\d*\.?\d+)?\)/);
    if (lightnessMatch && lightnessMatch[1]) {
      const lightness = parseInt(lightnessMatch[1]);
      return lightness > 70; // Arbitrary threshold for light HSL
    }
    return false;
  }
  else {
    return false; // Not a recognized color format
  }

  // Calculate luminance (simplified)
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance > 0.7; // Threshold for "light"
};


export const LiveFormPreview: React.FC<LiveFormPreviewProps> = ({
  formData,
  generatedForm,
  createdForm,
  user,
  extractedDesignTokens, // Use new prop
  extractedVoiceAnalysis, // Use new prop
}) => {
  const { url, purpose } = formData;

  const previewContainerRef = useRef<HTMLDivElement>(null); // Ref for the fixed-height container
  const formNaturalSizeRef = useRef<HTMLDivElement>(null); // Ref to measure the natural size of the form
  const [scale, setScale] = useState(1);
  const [currentFormHeight, setCurrentFormHeight] = useState('auto'); // To adjust the height of the scaled content

  // Construct a mock GeneratedForm for preview if not yet generated by AI
  const getPreviewForm = (): GeneratedForm => {
    if (generatedForm) {
      return generatedForm;
    }

    // Default styling, potentially overridden by extracted tokens
    const defaultStyling = {
      primaryColor: extractedDesignTokens?.primaryColors?.[0] || '#007bff',
      backgroundColor: extractedDesignTokens?.colorPalette?.find(color => isLightColor(color)) || '#f8f9fa', // Try to find a light color, else use app's light gray
      fontFamily: extractedDesignTokens?.fontFamilies?.[0] || 'system-ui, -apple-system, sans-serif',
      borderRadius: '8px',
      buttonStyle: 'solid',
      // Removed maxWidth from here, let the parent container manage it
    };

    // Mock fields based on purpose
    let mockFields: FormField[] = [
      { type: 'text', name: 'name', label: 'Your Name', placeholder: 'Enter your name', required: true },
      { type: 'email', name: 'email', label: 'Email', placeholder: 'your@email.com', required: true },
    ];

    if (purpose?.toLowerCase().includes('feedback') || purpose?.toLowerCase().includes('message')) {
      mockFields.push({ type: 'textarea', name: 'message', label: 'Message', placeholder: 'Your message', required: true });
    } else if (purpose?.toLowerCase().includes('lead')) {
      mockFields.push({ type: 'text', name: 'company', label: 'Company', placeholder: 'Your company', required: false });
    }

    // Use extracted messaging for description if available
    const descriptionText = extractedDesignTokens?.messaging?.[0] || 
                            (url ? `This form will adapt to the style of ${url}` : 'Start by entering a website URL.');

    return {
      title: purpose ? `AI Form: ${purpose}` : 'Your AI-Powered Form',
      description: descriptionText,
      fields: mockFields,
      ctaText: purpose?.toLowerCase().includes('subscribe') ? 'Subscribe' : 'Submit',
      thankYouMessage: 'Thank you for your submission!',
      styling: defaultStyling,
      // formLayout: 'inline', // Default to inline as other layouts are removed
    };
  };

  const previewForm = getPreviewForm();

  useEffect(() => {
    // This effect needs to run after the form content has rendered at its natural size
    // A small delay might be necessary to ensure DOM is fully updated
    const timer = setTimeout(() => {
      if (previewContainerRef.current && formNaturalSizeRef.current) {
        const containerHeight = previewContainerRef.current.clientHeight; // Available height of the fixed container
        const contentNaturalHeight = formNaturalSizeRef.current.scrollHeight; // Natural height of the form content
        const containerWidth = previewContainerRef.current.clientWidth; // Available width of the fixed container
        const contentNaturalWidth = formNaturalSizeRef.current.scrollWidth; // Natural width of the form content

        let newScale = 1;
        if (contentNaturalHeight > containerHeight || contentNaturalWidth > containerWidth) {
          const scaleY = containerHeight / contentNaturalHeight;
          const scaleX = containerWidth / contentNaturalWidth;
          newScale = Math.min(scaleY, scaleX); // Scale down to fit both dimensions
        }
        
        setScale(newScale);
        // Set the height of the scaled content wrapper to its scaled natural height
        setCurrentFormHeight(`${contentNaturalHeight * newScale}px`);
      }
    }, 50); // Small delay to allow DOM to settle

    return () => clearTimeout(timer);
  }, [previewForm, generatedForm, createdForm]); // Re-run when form data changes

  const formContent = (
    <EmbeddableForm
      form={previewForm}
      embedCode={createdForm?.embed_code || "preview-mode"}
      showBranding={false}
      onSubmit={(data) => console.log('Preview submission:', data)}
    />
  );

  return (
    <div className="card" style={{ position: 'sticky', top: '20px', maxWidth: '500px' }}>
      <h3 style={{ marginBottom: '16px', textAlign: 'center' }}>Live Preview</h3>
      <div
        ref={previewContainerRef}
        style={{
          border: '1px solid #e1e5e9',
          borderRadius: '8px',
          backgroundColor: '#f8f9fa',
          height: '60vh', // Fixed height for the preview window
          overflow: 'hidden', // Hide overflow, as we are scaling
          position: 'relative',
          display: 'flex',
          alignItems: 'center', // Center vertically if content is smaller
          justifyContent: 'center', // Center horizontally
        }}
      >
        {/* This div is to measure the natural size of the form before scaling */}
        <div
          ref={formNaturalSizeRef}
          style={{
            position: 'absolute', // Position absolutely to not affect parent layout
            visibility: 'hidden', // Hide it
            pointerEvents: 'none', // Disable pointer events
            width: '100%', // Allow it to take full width for measurement
            // No transform here, this is for measuring natural size
          }}
        >
          {formContent}
        </div>

        {/* This div applies the scaling and is visible */}
        <div
          style={{
            transform: `scale(${scale})`,
            transformOrigin: 'top center',
            width: '100%', // Allow it to take full width for scaling context
            height: currentFormHeight, // Adjust height based on scaling
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            flexShrink: 0,
          }}
        >
          {url || purpose || generatedForm ? (
            formContent
          ) : (
            <div style={{ textAlign: 'center', padding: '20px', color: '#666' }}>
              <div style={{ fontSize: '48px', marginBottom: '16px' }}>✨</div>
              <h4 style={{ fontSize: '18px', marginBottom: '8px', color: '#333' }}>Your AI-Powered Form</h4>
              <p style={{ fontSize: '14px', margin: '0' }}>
                Start by entering a website URL in the chat to the left to generate your form!
              </p>
            </div>
          )}
        </div>
      </div>
      {generatedForm && (
        <div style={{
          marginTop: '16px',
          padding: '12px',
          backgroundColor: '#e8f5e8',
          borderRadius: '6px',
          border: '1px solid #c3e6cb',
          textAlign: 'center',
          fontSize: '14px',
          color: '#155724'
        }}>
          ✅ AI-generated form preview.
        </div>
      )}
    </div>
  );
};